#!/usr/bin/env python3
"""Regenerate coreai_zoo_routes.py — the routing snapshot a pip install carries.

Run from a zoo checkout after adding or editing a recipe.toml, then commit both.
The snapshot holds only what route() reads: source ids, status, needs, overlay.
A live checkout always wins over it; see zoo_recipes() in coreai_export.py.
"""
from __future__ import annotations

import datetime
import pprint
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from coreai_export import zoo_recipes  # noqa: E402

FIELDS = ("family", "source_kind", "source_id", "source_hf_id", "status", "needs", "overlay")


def main() -> None:
    recipes, root, prov = zoo_recipes()
    if root is None:
        raise SystemExit("no zoo checkout found — the snapshot can only be built from one")
    routes = {name: {k: r[k] for k in FIELDS if r.get(k) is not None}
              for name, r in sorted(recipes.items())}
    date = datetime.date.today().isoformat()
    body = pprint.pformat(routes, width=96, sort_dicts=True)
    out = HERE / "coreai_zoo_routes.py"
    out.write_text(
        '"""The zoo\'s recorded recipes, snapshotted so a pip install can still route.\n'
        "\n"
        "Generated by make_zoo_routes.py from models/*/recipe.toml — do not edit by hand.\n"
        "A live zoo checkout always wins; coreai_export reads this only when\n"
        "find_zoo_root() comes back empty, and stamps the route SNAPSHOT rather than live.\n"
        '"""\n'
        "\n"
        f"DATE = {date!r}\n"
        f"ROUTES = {body}\n"
    )
    n_hf = sum(1 for r in routes.values() if r.get("source_kind") == "hf")
    print(f"{out.name}: {len(routes)} recipes ({n_hf} with an hf source), from {prov}")


if __name__ == "__main__":
    main()
