#!/usr/bin/env python3
"""Freeze the Shieldstral moderation suite for the on-device gate.

The phone has no tokenizer and no oracle, so both travel with the fixture: the
padded ids for each case and the fp32 P(violation) they must reproduce. The gate
in PipelinedBench (`PB_SHIELD`) reads exactly this file.

`real_len` rather than a mask array: the mask is `1 * real + 0 * (S - real)` by
construction, and a mask that disagrees with the ids is a failure mode nobody
would find.

Run (conversion venv):
    ../coreai-models/.venv/bin/python _smoke/dump_shieldstral_device_ref.py
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "conversion"))
from _paths import hf_snapshot  # noqa: E402
from _shieldstral_suite import SUITE  # noqa: E402
from export_shieldstral import render_prompt  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--hf-id", default="mistralai/Shieldstral-1.0-3B")
    ap.add_argument("--seq-len", type=int, default=512)
    ap.add_argument("--ref", default=str(Path(__file__).parent / "shieldstral_3b_suite_ref.npz"))
    ap.add_argument("--out", default=str(Path(__file__).parent / "shieldstral_ref"))
    ap.add_argument("--swift", default=None,
                    help="also emit the fixture as a Swift source for PipelinedBench")
    args = ap.parse_args()

    from tokenizers import Tokenizer

    snap = Path(hf_snapshot(args.hf_id))
    tok = Tokenizer.from_file(str(snap / "tokenizer.json"))
    pad_id = int(json.loads((snap / "config.json").read_text())["text_config"]["pad_token_id"])
    oracle = np.load(args.ref, allow_pickle=True)

    ids_all, lens, ps, labels, expected = [], [], [], [], []
    for i, (instr, query, doc, want_unsafe, label) in enumerate(SUITE):
        ids = tok.encode(render_prompt(instr, query, doc), add_special_tokens=False).ids
        if ids != oracle[f"case{i}_ids"].tolist():
            raise SystemExit(f"{label}: host prompt no longer matches the oracle ids")
        if len(ids) > args.seq_len:
            raise SystemExit(f"{label}: {len(ids)} tokens > grid {args.seq_len}")
        lens.append(len(ids))
        ids_all.append(ids + [pad_id] * (args.seq_len - len(ids)))
        ps.append(float(oracle[f"case{i}_p"]))
        labels.append(label)
        expected.append(int(want_unsafe))

    if args.swift:
        # Embed the fixture in PipelinedBench instead of sideloading it. Only the REAL ids
        # travel (the padding is `pad_token_id` repeated, which the gate can rebuild), so the
        # generated file is a few KB and the gate stops depending on a working file-transfer
        # tunnel -- which is the part of devicectl that fails first.
        lines = [
            "// Generated by _smoke/dump_shieldstral_device_ref.py -- do not edit.",
            "// The Shieldstral moderation suite: real prompt ids + the fp32 verdicts they must",
            "// reproduce. Embedded rather than sideloaded so the gate needs no file transfer.",
            "enum ShieldFixture {",
            f"    static let padTokenID: Int32 = {pad_id}",
            "    static let labels: [String] = [",
        ]
        lines += [f"        {l!r}," for l in labels]
        lines += ["    ]", "    static let expectedUnsafe: [Bool] = ["]
        lines += ["        " + ", ".join("true" if e else "false" for e in expected)]
        lines += ["    ]", "    static let pFP32: [Double] = ["]
        lines += ["        " + ", ".join(f"{p:.6f}" for p in ps)]
        lines += ["    ]", "    static let ids: [[Int32]] = ["]
        for i, (row, ln) in enumerate(zip(ids_all, lens)):
            body = ", ".join(str(t) for t in row[:ln])
            lines.append(f"        [{body}],   // {labels[i]}")
        lines += ["    ]", "}", ""]
        dest = Path(args.swift)
        dest.write_text("\n".join(lines).replace("'", '"'))
        print(f"wrote {dest} ({dest.stat().st_size / 1e3:.0f} KB)")

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "shield_ref.json").write_text(json.dumps({
        "model": args.hf_id,
        "seq_len": args.seq_len,
        "pad_token_id": pad_id,
        "cases": len(SUITE),
        "labels": labels,
        "expected_unsafe": expected,
        "real_len": lens,
        "p_fp32": ps,
        "ids": ids_all,
    }, indent=1))
    size = (out / "shield_ref.json").stat().st_size
    print(f"wrote {out / 'shield_ref.json'} ({size / 1e3:.0f} KB, "
          f"{len(SUITE)} cases, S={args.seq_len})")
    for lab, ln, p in zip(labels, lens, ps):
        print(f"  {lab:26s} {ln:>4} tok  P={p:.4f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
